# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13cb5c0627be2fa9868f9eeb6fa2e635266d55fd9023efcdbed18a02e35e20fc7a19336636f25ff4ed90fa2d9f01dd8194af5433ba27b74ff0deb113e0c87c9d

test:
  secret_key_base: 764a3c394591f2463ec534ffed7f5367b33c768bba759222989c0e08603ad1e93fa59dff0aa0408805fb9731d88e00207a242702258a740af359dee745cc0a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
